fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
      ref: "6.3.0"
    zypprepo:
      repo: "https://github.com/voxpupuli/puppet-zypprepo"
  symlinks:
    "google_chrome": "#{source_dir}"
